name: CI-coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: Run PHPUnit Tests with coverage
        uses: php-actions/phpunit@v2
        with:
          php_extensions: xdebug
          php_version: "7.4"
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage